version: '2.1'
services:


  config:
    image: saurseth/samplemicroservice-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery:
    image: saurseth/samplemicroservice-discovery
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: saurseth/samplemicroservice-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  hello-service:
    image: saurseth/samplemicroservice-hello-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"




